feat: add basic support openApi 3.1
Redocly/openapi-cli pull request #280
Opened 2021-04-13 16:16 UTC by AlexVarchuk

fixes https://github.com/Redocly/openapi-cli/issues/276

[files for testing](https://github.com/Redocly/openapi-cli/files/6305201/openapi-3.1-examples.zip)

2021-04-14 07:21 UTC, andriyl approved these changes

2021-04-14 08:03 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +    'x-webhooks': 'WebhooksMap',
No need for x-webhooks

2021-04-14 08:07 UTC, RomanHotsiy requested changes
Left a bunch of comments.

2021-04-14 08:07 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +    'x-webhooks': 'WebhooksMap',
No need for x-webhooks in 3.1
```suggestion
```

2021-04-14 08:07 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +    webhooks: 'Webhooks',
```suggestion
    webhooks: 'WebhooksMap',
```

2021-04-14 08:07 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +const Tag: NodeType = {
can we reuse shared types from oas3.0 ?

2021-04-14 08:07 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +};
```suggestion
```

2021-04-14 08:07 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +      return {
formatting

2021-04-14 08:07 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +const Schema: NodeType = {
you should add more fields here, new json schema draft supports `if`, `else`, `const`, etc.

2021-04-14 08:07 UTC, RomanHotsiy commented on packages/core/src/types/oas3_1.ts
> +    type: { enum: ['apiKey', 'http', 'oauth2', 'openIdConnect'] },
There is one more added I think, `mutualTls`

2021-04-14 09:46 UTC, Marshevskyy reviewed
good job Alex!

it would be amazing to add some tests which can cover this functionality,
we do not need to cover some implementation, 
but we should cover behavior

ideally we should somehow pass as an input OAS 3.1 and got it valid in linter....

2021-04-14 10:54 UTC, AlexVarchuk commented
> good job Alex!
> 
> it would be amazing to add some tests which can cover this functionality,
> we do not need to cover some implementation,
> but we should cover behavior
> 
> ideally we should somehow pass as an input OAS 3.1 and got it valid in linter....

Good idea. I will try to implement it.

2021-04-14 14:31 UTC, AlexVarchuk commented
@RomanHotsiy @Marshevskyy Please check it again. Thanks.

2021-04-22 12:46 UTC, Marshevskyy approved these changes
Alex! well done! 
tests 💪🏼 

but before merge, I would like to get approval from @RomanHotsiy

2021-04-22 12:53 UTC, timbunce commented
Just a note from a random bystander to say Thanks Alex! Looking forward to using this.

2021-05-17 09:23 UTC, RomanHotsiy approved these changes
Good job 👏

2021-05-17 09:24 UTC, merged