Docs: added a combined page with login-logout commands instead of separate pages
Redocly/openapi-cli pull request #351
Opened 2021-08-29 20:25 UTC by bandantonio

## What/Why/How?

## Reference

## Testing

## Screenshots (optional)

## Check yourself

- [ ] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [ ] All new/updated code is covered with tests

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

2021-09-01 11:32 UTC, swapnilogale requested changes
As discussed, let us split out this topic into individual `login` and `logout` pages

2021-09-04 01:22 UTC, adamaltman commented on docs/commands/login.md
> +Before proceeding with the command, you must [generate a personal API key](../../workflows/personal-api-keys.md) first.
```suggestion
Before proceeding with the command, [generate a personal API key](../../workflows/personal-api-keys.md).
```

(I'm trying to shorten/simplify)

2021-09-06 13:56 UTC, skadinna requested changes

2021-09-06 13:56 UTC, skadinna commented on docs/commands/login.md
> +option      | type      | required? | default | description
```suggestion
Option      |  Type      |  Required | Default | Description
```

2021-09-06 13:56 UTC, skadinna commented on docs/commands/login.md
> +`--verbose` | `boolean` | no        | -       | Include addtional output
```suggestion
`--verbose` | `boolean` | no        | -       | Include additional output
```

2021-09-06 13:56 UTC, skadinna commented on docs/commands/logout.md
> +option      | type      | required? | default | description
```suggestion
Option      | Type      | Required | Default | Description
```

2021-09-07 10:05 UTC, skadinna approved these changes

2021-09-08 11:07 UTC, swapnilogale approved these changes
@bandantonio just a small style fix, but everthing else looks good

2021-09-08 11:15 UTC, merged