Update installation.md
Redocly/openapi-cli pull request #578
Opened 2022-03-06 01:50 UTC by JodyWinter

## What/Why/How?
Substantive edit of this page.

## Reference

## Testing
Fully tested npm global method, as discussed. Other methods will need testing.

## Screenshots (optional)

## Check yourself

- [ ] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [ ] All new/updated code is covered with tests

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

2022-03-07 12:19 UTC, skadinna requested changes

2022-03-07 12:19 UTC, skadinna commented on docs/installation.md
> +There are two methods that you can use to install OpenAPI CLI: global and runtime.
```suggestion
There are two methods you can use to install OpenAPI CLI: global and runtime.
```

2022-03-07 12:19 UTC, skadinna commented on docs/installation.md
> +There are two methods that you can use to install OpenAPI CLI: global and runtime.
Or even just "There are two ways to install" if we want to simplify it further.

2022-03-07 12:19 UTC, skadinna commented on docs/installation.md
> +Go back to the [Quickstart guide](./docs/quickstart.md) and finish it.
issue: The quickstart guide should not require the user to switch back and forth between pages. In this section, we should recommend going to the configuration file and learning how to adjust it, and/or reading more about the supported commands and using them.

2022-03-07 12:19 UTC, skadinna commented on docs/installation.md
> +After a successful install, you should set up tab completion for the terminal. Generate the completion script using the following command:
question: Do you think we could somehow indicate that this is not required? Tab completion is a convenient option that makes using OpenAPI CLI easier and faster, but it's not like the tool won't work without it. Our current docs are not great at indicating this...

2022-03-17 15:48 UTC, skadinna approved these changes

2022-03-24 03:20 UTC, swapnilogale approved these changes
Looks great @JodyWinter. Simplifies the installation process substantially! Well done.

2022-03-24 03:25 UTC, merged