feat: Mock Server config
Redocly/openapi-cli pull request #594
Opened 2022-03-15 11:01 UTC by BohdanPetryshyn

## What/Why/How?
This PR adds mock server options to `.redocly.yaml` schema.

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [x] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

2022-03-15 11:16 UTC, ohorbachevskyi approved these changes

2022-03-15 11:30 UTC, tatomyr approved these changes

2022-03-15 14:37 UTC, RomanHotsiy requested changes
Let's add it into new config format better. I'll manage this.

2022-03-16 15:38 UTC, tatomyr commented on packages/core/src/types/redocly-yaml.ts
> +    mockServer: 'ConfigMockServer',
```suggestion
    'features.mockServer': 'ConfigMockServer',
```

2022-03-16 15:38 UTC, tatomyr commented on packages/core/src/types/redocly-yaml.ts
> +    mockServer: 'ConfigMockServer',
```suggestion
    'features.mockServer': 'ConfigMockServer',
```

2022-03-17 04:52 UTC, RomanHotsiy approved these changes

2022-03-17 19:31 UTC, merged